# Generated by Django 5.0.6 on 2024-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='desh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desh_name', models.CharField(max_length=50)),
                ('desh_age', models.IntegerField()),
            ],
        ),
    ]
