# Generated by Django 5.0.6 on 2024-05-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='desh',
            new_name='Desh_inf',
        ),
    ]
